set RRUN= C:\r\R-3.3.2\bin\x64\Rscript.exe
set RJOB= \\40278DFWYM13\Na\node.R


START CMD /C CALL %RRUN% %RJOB% 1
START CMD /C CALL %RRUN% %RJOB% 2
START CMD /C CALL %RRUN% %RJOB% 3
START CMD /C CALL %RRUN% %RJOB% 4
START CMD /C CALL %RRUN% %RJOB% 5
START CMD /C CALL %RRUN% %RJOB% 6
START CMD /C CALL %RRUN% %RJOB% 7
